const PRODUCTS = [
  {
    id: "airpods-max",
    name: "Auraluxe Max Headphones",
    category: "Audio",
    price: 549,
    oldPrice: 629,
    rating: 4.9,
    stock: 18,
    badge: "Best Seller",
    image: "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=900&q=80",
    accent: "#2563eb",
    description: "Studio-grade wireless headphones with adaptive noise cancellation and precision spatial audio.",
    specs: ["40 hour battery", "Active noise cancellation", "Memory foam cushions", "Bluetooth 5.3"]
  },
  {
    id: "ultrabook-pro",
    name: "Nimbus Pro 14 Laptop",
    category: "Computers",
    price: 1499,
    oldPrice: 1699,
    rating: 4.8,
    stock: 9,
    badge: "New",
    image: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=80",
    accent: "#10b981",
    description: "A thin performance laptop built for design work, development, and everyday creative production.",
    specs: ["14 inch liquid display", "1TB SSD", "32GB unified memory", "All-day battery"]
  },
  {
    id: "smart-watch",
    name: "PulseOne Smart Watch",
    category: "Wearables",
    price: 329,
    oldPrice: 399,
    rating: 4.7,
    stock: 25,
    badge: "Popular",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80",
    accent: "#f59e0b",
    description: "A polished health and productivity watch with advanced sensors and elegant daily tracking.",
    specs: ["ECG ready", "Sleep insights", "Water resistant", "7 day battery"]
  },
  {
    id: "camera-kit",
    name: "Frame X Mirrorless Kit",
    category: "Cameras",
    price: 1189,
    oldPrice: 1299,
    rating: 4.8,
    stock: 7,
    badge: "Creator Pick",
    image: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=900&q=80",
    accent: "#ef4444",
    description: "A compact mirrorless camera bundle for crisp product shots, travel reels, and portrait sessions.",
    specs: ["26MP sensor", "4K 60 video", "Weather sealed", "Fast autofocus"]
  },
  {
    id: "desk-lamp",
    name: "Lumina Desk Lamp",
    category: "Home Office",
    price: 129,
    oldPrice: 159,
    rating: 4.6,
    stock: 31,
    badge: "Eco",
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=80",
    accent: "#2563eb",
    description: "A minimalist LED task lamp with ambient dimming and a warm reading mode.",
    specs: ["Touch dimmer", "USB-C charging", "Aluminum body", "Low heat LED"]
  },
  {
    id: "sneaker",
    name: "Velocity Knit Sneaker",
    category: "Lifestyle",
    price: 178,
    oldPrice: 220,
    rating: 4.7,
    stock: 42,
    badge: "Limited",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=80",
    accent: "#10b981",
    description: "Lightweight all-day sneakers with responsive cushioning and a breathable knit upper.",
    specs: ["Cloud foam sole", "Recycled knit", "Urban grip", "True-to-size fit"]
  },
  {
    id: "speaker",
    name: "SoundBarrel Mini",
    category: "Audio",
    price: 219,
    oldPrice: 259,
    rating: 4.5,
    stock: 14,
    badge: "Portable",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=900&q=80",
    accent: "#f59e0b",
    description: "A compact speaker with room-filling sound, rugged build, and rich bass response.",
    specs: ["360 degree audio", "IP67 shell", "Pairing mode", "18 hour battery"]
  },
  {
    id: "chair",
    name: "ErgoFlow Office Chair",
    category: "Home Office",
    price: 439,
    oldPrice: 499,
    rating: 4.8,
    stock: 11,
    badge: "Ergonomic",
    image: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&w=900&q=80",
    accent: "#2563eb",
    description: "A premium ergonomic chair with breathable support for long focus sessions.",
    specs: ["4D arm rests", "Dynamic lumbar", "Mesh back", "Quiet casters"]
  }
];

const CATEGORIES = ["All", ...new Set(PRODUCTS.map((product) => product.category))];
